spring:
  profiles:
  application:
    name: betpawa_server
   
     
  datasource:
    url: jdbc:mysql://localhost:3306/betpawa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 1000
      maximum-pool-size: 10
      minimum-idle: 1
      idleTimeout: 3000
      connectionTimeout: 30000
      maxLifetime: 1800000
      pool-name: bpServerMYSQLConnectionPool
      auto-commit: false
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 9011
serverprop:
   port: 8777
 

